// ===== Configuration =====
// DOC_TITLES 从 NAV_SECTIONS 动态生成（build.py 打包时自动生成）
const DOC_TITLES = {};
if (typeof NAV_SECTIONS !== 'undefined') {
  NAV_SECTIONS.forEach(section => {
    section.items.forEach(item => {
      DOC_TITLES[item.file] = item.title;
    });
  });
}

// ===== Track State =====
let currentTrack = localStorage.getItem('track') || 'ai';

// ===== DOM Elements =====
const sidebar = document.getElementById('sidebar');
const menuToggle = document.getElementById('menuToggle');
const article = document.getElementById('article');
const loading = document.getElementById('loading');
const docTitle = document.getElementById('docTitle');
const tocNav = document.getElementById('tocNav');
const themeToggle = document.getElementById('themeToggle');
const scrollTopBtn = document.getElementById('scrollTop');
const contentBody = document.getElementById('contentBody');
const hljsLight = document.getElementById('hljs-light');
const hljsDark = document.getElementById('hljs-dark');

let currentFile = null;

// ===== Track Switcher =====
function initTrackSwitcher() {
  const switcher = document.getElementById('trackSwitcher');
  if (!switcher) return;
  
  // Set initial state
  switcher.querySelectorAll('.track-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.track === currentTrack);
    btn.addEventListener('click', () => {
      if (btn.dataset.track === currentTrack) return;
      currentTrack = btn.dataset.track;
      localStorage.setItem('track', currentTrack);
      switcher.querySelectorAll('.track-btn').forEach(b => b.classList.toggle('active', b === btn));
      buildNavigation();
      // Load first doc in new track
      const firstSection = NAV_SECTIONS.find(s => s.track === currentTrack || s.track === 'shared');
      if (firstSection && firstSection.items.length) {
        loadDocument(firstSection.items[0].file);
      }
    });
  });
}

// ===== Build Sidebar Navigation =====
function buildNavigation() {
  const navContainer = document.getElementById('navContainer');
  if (!navContainer || typeof NAV_SECTIONS === 'undefined') return;

  let html = '';
  NAV_SECTIONS.filter(s => s.track === currentTrack || s.track === 'shared').forEach(section => {
    html += `<div class="nav-section"><h3>${section.title}</h3>`;
    section.items.forEach(item => {
      html += `<a class="nav-item" data-file="${item.file}" href="#">`;
      html += `<span class="nav-text">${item.title}</span>`;
      html += `</a>`;
    });
    html += `</div>`;
  });

  navContainer.innerHTML = html;

  // 绑定点击事件
  navContainer.querySelectorAll('.nav-item').forEach(item => {
    item.addEventListener('click', (e) => {
      e.preventDefault();
      const file = item.dataset.file;
      if (file) loadDocument(file);
    });
  });
}

// ===== Markdown Rendering =====
marked.setOptions({
  highlight: function (code, lang) {
    if (lang && hljs.getLanguage(lang)) {
      return hljs.highlight(code, { language: lang }).value;
    }
    return hljs.highlightAuto(code).value;
  },
  breaks: false,
  gfm: true,
});

// Custom renderer for code blocks with language labels
const renderer = new marked.Renderer();
const originalCodeRenderer = renderer.code;

renderer.code = function(code, language, escaped) {
  const lang = (language || '').trim();
  let highlighted;
  if (lang && hljs.getLanguage(lang)) {
    highlighted = hljs.highlight(code, { language: lang }).value;
  } else {
    highlighted = hljs.highlightAuto(code).value;
  }
  const langAttr = lang ? ` data-lang="${lang}"` : '';
  return `<pre${langAttr}><code class="hljs language-${lang}">${highlighted}</code></pre>`;
};

// Handle checkboxes in markdown
renderer.listitem = function(text) {
  if (text.startsWith('<input')) {
    return `<li style="list-style:none;margin-left:-20px">${text}</li>\n`;
  }
  return `<li>${text}</li>\n`;
};

marked.setOptions({ renderer });

// ===== Load Document =====
function loadDocument(filename, searchQuery) {
  if (currentFile === filename && !searchQuery) return;
  currentFile = filename;

  // Update nav active state
  document.querySelectorAll('.nav-item').forEach(item => {
    item.classList.toggle('active', item.dataset.file === filename);
  });

  // Update title
  docTitle.textContent = DOC_TITLES[filename] || filename;

  // Load from bundled DOCS object (generated by build.py)
  if (typeof DOCS === 'undefined') {
    article.innerHTML = `
      <div style="text-align:center;padding:60px 0;color:var(--text-secondary)">
        <p style="font-size:48px;margin-bottom:16px">📦</p>
        <p>请先运行打包脚本生成 docs.js</p>
        <pre style="text-align:left;max-width:400px;margin:20px auto;padding:16px;background:var(--code-bg);border-radius:8px;font-size:13px">python build.py</pre>
        <p style="font-size:13px;margin-top:8px">或直接双击 <b>启动网站.bat</b></p>
      </div>`;
    return;
  }

  const text = DOCS[filename];
  if (!text) {
    article.innerHTML = `
      <div style="text-align:center;padding:60px 0;color:var(--text-secondary)">
        <p style="font-size:48px;margin-bottom:16px">📄</p>
        <p>文档未找到: ${filename}</p>
        <p style="font-size:13px;margin-top:8px">请重新运行 <b>python build.py</b> 打包</p>
      </div>`;
    return;
  }

  // Render markdown
  article.innerHTML = marked.parse(text);

  // Build table of contents
  buildTOC();

  // Highlight and scroll to search match
  if (searchQuery) {
    highlightAndScroll(searchQuery);
  } else {
    // Scroll to top
    contentBody.scrollTop = 0;
    window.scrollTo(0, 0);
  }

  // Save current doc to URL hash
  window.location.hash = encodeURIComponent(filename);

  // Close mobile sidebar
  sidebar.classList.remove('open');
}

// ===== Table of Contents =====
function buildTOC() {
  const headings = article.querySelectorAll('h2, h3');
  let tocHTML = '';

  headings.forEach((h, i) => {
    const id = `heading-${i}`;
    h.id = id;
    const level = h.tagName.toLowerCase();
    const cls = level === 'h3' ? ' toc-h3' : '';
    tocHTML += `<a href="#${id}" class="${cls}" data-id="${id}">${h.textContent}</a>`;
  });

  tocNav.innerHTML = tocHTML;

  // TOC click handler
  tocNav.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const target = document.getElementById(link.dataset.id);
      if (target) {
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });
}

// ===== Scroll spy for TOC =====
let scrollTimeout;
window.addEventListener('scroll', () => {
  clearTimeout(scrollTimeout);
  scrollTimeout = setTimeout(() => {
    const headings = article.querySelectorAll('h2, h3');
    let activeId = null;

    headings.forEach(h => {
      const rect = h.getBoundingClientRect();
      if (rect.top <= 100) {
        activeId = h.id;
      }
    });

    tocNav.querySelectorAll('a').forEach(link => {
      link.classList.toggle('active', link.dataset.id === activeId);
    });
  }, 50);
});

// ===== Theme Toggle =====
function setTheme(dark) {
  document.documentElement.setAttribute('data-theme', dark ? 'dark' : 'light');
  themeToggle.textContent = dark ? '☀️' : '🌙';
  hljsLight.disabled = dark;
  hljsDark.disabled = !dark;
  localStorage.setItem('theme', dark ? 'dark' : 'light');
}

themeToggle.addEventListener('click', () => {
  const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
  setTheme(!isDark);
});

// Load saved theme
const savedTheme = localStorage.getItem('theme');
if (savedTheme === 'dark') {
  setTheme(true);
}

// ===== Scroll to Top =====
scrollTopBtn.addEventListener('click', () => {
  window.scrollTo({ top: 0, behavior: 'smooth' });
});

// ===== Mobile Menu =====
menuToggle.addEventListener('click', () => {
  sidebar.classList.toggle('open');
});

// Close sidebar when clicking outside on mobile
document.addEventListener('click', (e) => {
  if (window.innerWidth <= 768 &&
      sidebar.classList.contains('open') &&
      !sidebar.contains(e.target) &&
      e.target !== menuToggle) {
    sidebar.classList.remove('open');
  }
});

// ===== Global Search =====
const searchInput = document.getElementById('searchInput');
const searchOverlay = document.getElementById('searchOverlay');
const searchResults = document.getElementById('searchResults');
const searchShortcut = document.getElementById('searchShortcut');

let searchIndex = null; // cached search index
let selectedResultIdx = -1;

// Build search index from DOCS
function buildSearchIndex() {
  if (searchIndex || typeof DOCS === 'undefined') return;
  searchIndex = [];
  for (const [filename, content] of Object.entries(DOCS)) {
    const title = DOC_TITLES[filename] || filename;
    // Find which section this doc belongs to
    let sectionName = '';
    if (typeof NAV_SECTIONS !== 'undefined') {
      for (const sec of NAV_SECTIONS) {
        if (sec.items.some(it => it.file === filename)) {
          sectionName = sec.title;
          break;
        }
      }
    }
    searchIndex.push({ filename, title, sectionName, content: content.toLowerCase(), rawContent: content });
  }
}

// Perform search
function performSearch(query) {
  if (!query || query.length < 2) {
    searchResults.innerHTML = `<div class="search-hint">输入至少 2 个字符开始搜索</div>`;
    searchOverlay.classList.remove('active');
    selectedResultIdx = -1;
    return;
  }

  buildSearchIndex();
  if (!searchIndex) return;

  const q = query.toLowerCase();
  const results = [];

  for (const item of searchIndex) {
    // Search in title and content
    const titleMatch = item.title.toLowerCase().includes(q);
    const contentIdx = item.content.indexOf(q);

    if (titleMatch || contentIdx !== -1) {
      // Extract snippet around match
      let snippet = '';
      if (contentIdx !== -1) {
        const start = Math.max(0, contentIdx - 40);
        const end = Math.min(item.rawContent.length, contentIdx + query.length + 80);
        const raw = item.rawContent.slice(start, end);
        // Remove markdown syntax for cleaner display
        snippet = raw.replace(/[#*`\[\]()_~>|]/g, '').replace(/\n/g, ' ').trim();
        if (start > 0) snippet = '…' + snippet;
        if (end < item.rawContent.length) snippet += '…';
      } else {
        // Title-only match, show first 120 chars of content
        snippet = item.rawContent.slice(0, 120).replace(/[#*`\[\]()_~>|]/g, '').replace(/\n/g, ' ').trim() + '…';
      }

      // Count total matches
      let count = 0;
      let pos = 0;
      while ((pos = item.content.indexOf(q, pos)) !== -1) {
        count++;
        pos += q.length;
      }

      results.push({
        filename: item.filename,
        title: item.title,
        section: item.sectionName,
        snippet,
        count,
        titleMatch
      });
    }
  }

  // Sort: title matches first, then by match count
  results.sort((a, b) => {
    if (a.titleMatch !== b.titleMatch) return b.titleMatch - a.titleMatch;
    return b.count - a.count;
  });

  renderSearchResults(results, query);
}

// Render results
function renderSearchResults(results, query) {
  selectedResultIdx = -1;

  if (results.length === 0) {
    searchResults.innerHTML = `
      <div class="search-empty">
        <div class="icon">🔍</div>
        <div>没有找到匹配「${escapeHTML(query)}」的结果</div>
      </div>`;
    searchOverlay.classList.add('active');
    return;
  }

  const escapedQuery = escapeHTML(query);
  const re = new RegExp(`(${escapeRegex(query)})`, 'gi');

  let html = `<div class="search-count">找到 ${results.length} 篇文档</div>`;
  results.forEach((r, i) => {
    const highlightedTitle = r.title.replace(re, '<mark>$1</mark>');
    const highlightedSnippet = r.snippet.replace(re, '<mark>$1</mark>');
    html += `
      <div class="search-result-item" data-file="${r.filename}" data-idx="${i}">
        <div class="search-result-title">${highlightedTitle}</div>
        ${r.section ? `<div class="search-result-section">${r.section} · ${r.count} 处匹配</div>` : ''}
        <div class="search-result-snippet">${highlightedSnippet}</div>
      </div>`;
  });

  searchResults.innerHTML = html;
  searchOverlay.classList.add('active');

  // Bind click on results
  searchResults.querySelectorAll('.search-result-item').forEach(el => {
    el.addEventListener('click', () => {
      const file = el.dataset.file;
      const q = searchInput.value.trim();
      closeSearch();
      loadDocument(file, q);
    });
  });
}

// Open / close search
function openSearch() {
  searchInput.focus();
  if (searchInput.value.length >= 2) {
    searchOverlay.classList.add('active');
  }
}

function closeSearch() {
  searchOverlay.classList.remove('active');
  searchInput.blur();
  selectedResultIdx = -1;
}

// Debounce helper
function debounce(fn, delay) {
  let timer;
  return function (...args) {
    clearTimeout(timer);
    timer = setTimeout(() => fn.apply(this, args), delay);
  };
}

// Escape HTML
function escapeHTML(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Escape regex special chars
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Highlight search query in article and scroll to first match
function highlightAndScroll(query) {
  if (!query) return;

  // Remove previous search highlights
  article.querySelectorAll('mark.search-hl').forEach(m => {
    const parent = m.parentNode;
    parent.replaceChild(document.createTextNode(m.textContent), m);
    parent.normalize();
  });

  const re = new RegExp(escapeRegex(query), 'gi');
  const walker = document.createTreeWalker(article, NodeFilter.SHOW_TEXT, null);
  const matches = [];

  // Collect all text nodes that contain the query
  while (walker.nextNode()) {
    const node = walker.currentNode;
    if (re.test(node.nodeValue)) {
      matches.push(node);
      re.lastIndex = 0; // reset regex
    }
  }

  if (matches.length === 0) {
    contentBody.scrollTop = 0;
    window.scrollTo(0, 0);
    return;
  }

  // Highlight all matches (wrap in <mark>)
  let firstMark = null;
  matches.forEach(textNode => {
    const fragment = document.createDocumentFragment();
    let lastIdx = 0;
    const text = textNode.nodeValue;
    let match;
    re.lastIndex = 0;
    while ((match = re.exec(text)) !== null) {
      // Text before match
      if (match.index > lastIdx) {
        fragment.appendChild(document.createTextNode(text.slice(lastIdx, match.index)));
      }
      // Highlighted match
      const mark = document.createElement('mark');
      mark.className = 'search-hl';
      mark.textContent = match[0];
      fragment.appendChild(mark);
      if (!firstMark) firstMark = mark;
      lastIdx = re.lastIndex;
    }
    // Remaining text
    if (lastIdx < text.length) {
      fragment.appendChild(document.createTextNode(text.slice(lastIdx)));
    }
    textNode.parentNode.replaceChild(fragment, textNode);
  });

  // Scroll to first match
  if (firstMark) {
    setTimeout(() => {
      firstMark.scrollIntoView({ behavior: 'smooth', block: 'center' });
    }, 50);
  }
}

// Navigate results with arrow keys
function navigateResults(direction) {
  const items = searchResults.querySelectorAll('.search-result-item');
  if (items.length === 0) return;

  items.forEach(el => el.classList.remove('selected'));

  if (direction === 'down') {
    selectedResultIdx = (selectedResultIdx + 1) % items.length;
  } else {
    selectedResultIdx = selectedResultIdx <= 0 ? items.length - 1 : selectedResultIdx - 1;
  }

  items[selectedResultIdx].classList.add('selected');
  items[selectedResultIdx].scrollIntoView({ block: 'nearest' });
}

// Event listeners
searchInput.addEventListener('input', debounce(() => {
  performSearch(searchInput.value.trim());
}, 250));

searchInput.addEventListener('focus', () => {
  searchShortcut.style.display = 'none';
  if (searchInput.value.trim().length >= 2) {
    performSearch(searchInput.value.trim());
  }
});

searchInput.addEventListener('blur', () => {
  searchShortcut.style.display = '';
  // Delay close so click on result works
  setTimeout(() => {
    if (!searchResults.matches(':hover')) {
      closeSearch();
    }
  }, 200);
});

searchOverlay.addEventListener('click', (e) => {
  if (e.target === searchOverlay) closeSearch();
});

// ===== Keyboard Shortcuts =====
document.addEventListener('keydown', (e) => {
  // Ctrl+K to focus search
  if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
    e.preventDefault();
    openSearch();
    return;
  }

  // When search is focused
  if (document.activeElement === searchInput) {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      navigateResults('down');
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      navigateResults('up');
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const items = searchResults.querySelectorAll('.search-result-item');
      const q = searchInput.value.trim();
      if (selectedResultIdx >= 0 && items[selectedResultIdx]) {
        const file = items[selectedResultIdx].dataset.file;
        closeSearch();
        loadDocument(file, q);
      } else if (items.length > 0) {
        const file = items[0].dataset.file;
        closeSearch();
        loadDocument(file, q);
      }
    } else if (e.key === 'Escape') {
      closeSearch();
    }
    return;
  }

  // Escape closes sidebar on mobile
  if (e.key === 'Escape') {
    sidebar.classList.remove('open');
  }
});

// ===== Initialize =====
function init() {
  initTrackSwitcher();
  
  // Check if hash belongs to a different track
  const hash = decodeURIComponent(window.location.hash.slice(1));
  if (hash && DOC_TITLES[hash]) {
    // Find which track this doc belongs to
    const docSection = NAV_SECTIONS.find(s => s.items.some(i => i.file === hash));
    if (docSection && docSection.track !== 'shared' && docSection.track !== currentTrack) {
      currentTrack = docSection.track;
      localStorage.setItem('track', currentTrack);
      document.querySelectorAll('.track-btn').forEach(b => {
        b.classList.toggle('active', b.dataset.track === currentTrack);
      });
    }
  }
  
  buildNavigation();

  const defaultFile = (typeof NAV_SECTIONS !== 'undefined' && NAV_SECTIONS.length > 0)
    ? NAV_SECTIONS.filter(s => s.track === currentTrack || s.track === 'shared')[0]?.items[0]?.file
    : null;

  if (hash && DOC_TITLES[hash]) {
    loadDocument(hash);
  } else if (defaultFile) {
    loadDocument(defaultFile);
  }
}

// Handle hash change
window.addEventListener('hashchange', () => {
  const hash = decodeURIComponent(window.location.hash.slice(1));
  if (hash && DOC_TITLES[hash]) {
    loadDocument(hash);
  }
});

init();
